// <auto-generated />
using System;
using Doto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doto.Infrastructure.Migrations
{
    [DbContext(typeof(DotoDbContext))]
    [Migration("20260729002439_AddAuthUsersForeignKey")]
    partial class AddAuthUsersForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Doto.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_url");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("height_cm");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("time_zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_app_users_email");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_app_users_parent_id")
                        .HasFilter("parent_id IS NOT NULL");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_app_users_role");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_app_users_username");

                    b.ToTable("app_users", "public", t =>
                        {
                            t.HasCheckConstraint("ck_app_users_no_self_parent", "parent_id IS DISTINCT FROM id");

                            t.HasCheckConstraint("ck_app_users_role_parent_coherence", "(role = 'Child' AND parent_id IS NOT NULL) OR (role = 'Parent' AND parent_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.ChildInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid>("ChildUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("InviteTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invite_token_hash");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_email");

                    b.Property<DateTime?>("LastSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at_utc");

                    b.Property<Guid>("ParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_user_id");

                    b.Property<int>("ResentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("resent_count");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TempPasswordSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("temp_password_sent_at");

                    b.HasKey("Id")
                        .HasName("pk_child_invites");

                    b.HasIndex("ChildUserId")
                        .HasDatabaseName("ix_child_invites_child_user_id");

                    b.HasIndex("ParentUserId", "InvitedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_child_invites_pending_email")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("Status", "ExpiresAtUtc")
                        .HasDatabaseName("ix_child_invites_status_expires_at_utc");

                    b.ToTable("child_invites", "public");
                });

            modelBuilder.Entity("Doto.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("app_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("push_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("PushToken")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_push_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_user_id")
                        .HasFilter("is_active");

                    b.ToTable("devices", "public");
                });

            modelBuilder.Entity("Doto.Domain.Entities.DoseOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<int>("GenerationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("generation_version");

                    b.Property<bool>("IsRetroactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_retroactive");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OccurrenceIndex")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_index");

                    b.Property<DateTime>("OriginalScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_scheduled_at_utc");

                    b.Property<string>("RecordSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("record_source");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<DateOnly>("ScheduledLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_local_date");

                    b.Property<TimeOnly>("ScheduledLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_local_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersededByOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_occurrence_id");

                    b.Property<DateTime?>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_dose_occurrences");

                    b.HasIndex("RecordedByUserId")
                        .HasDatabaseName("ix_dose_occurrences_recorded_by_user_id");

                    b.HasIndex("SupersededByOccurrenceId")
                        .HasDatabaseName("ix_dose_occurrences_superseded_by_occurrence_id");

                    b.HasIndex("MedicationId", "ScheduledAtUtc")
                        .HasDatabaseName("ix_dose_occurrences_medication_id_scheduled_at_utc");

                    b.HasIndex("Status", "ScheduledAtUtc")
                        .HasDatabaseName("ix_dose_occurrences_pending_scheduled_at_utc")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("UserId", "ScheduledLocalDate")
                        .HasDatabaseName("ix_dose_occurrences_user_id_scheduled_local_date");

                    b.HasIndex("ScheduleId", "GenerationVersion", "OccurrenceIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_dose_occurrences_schedule_generation_index");

                    b.ToTable("dose_occurrences", "public", t =>
                        {
                            t.HasCheckConstraint("ck_dose_occurrences_generation_version", "generation_version >= 1");

                            t.HasCheckConstraint("ck_dose_occurrences_occurrence_index", "occurrence_index >= 0");

                            t.HasCheckConstraint("ck_dose_occurrences_superseded_requires_target", "status <> 'Superseded' OR superseded_by_occurrence_id IS NOT NULL");

                            t.HasCheckConstraint("ck_dose_occurrences_taken_requires_instant", "status <> 'Taken' OR taken_at_utc IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.HealthCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("DiagnosedOn")
                        .HasColumnType("date")
                        .HasColumnName("diagnosed_on");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_health_conditions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_health_conditions_user_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("health_conditions", "public");
                });

            modelBuilder.Entity("Doto.Domain.Entities.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DosageUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dosage_unit");

                    b.Property<decimal>("DosageValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("dosage_value");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<int?>("TotalDoses")
                        .HasColumnType("integer")
                        .HasColumnName("total_doses");

                    b.Property<DateOnly?>("TreatmentEndDate")
                        .HasColumnType("date")
                        .HasColumnName("treatment_end_date");

                    b.Property<DateOnly>("TreatmentStartDate")
                        .HasColumnType("date")
                        .HasColumnName("treatment_start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_medications");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_medications_user_id_is_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("medications", "public", t =>
                        {
                            t.HasCheckConstraint("ck_medications_dosage_positive", "dosage_value > 0");

                            t.HasCheckConstraint("ck_medications_treatment_period", "treatment_end_date IS NULL OR treatment_end_date >= treatment_start_date");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.MedicationSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<TimeOnly?>("AnchorTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("anchor_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short?>("DayOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_month");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("DosesPerDay")
                        .HasColumnType("smallint")
                        .HasColumnName("doses_per_day");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly?>("GeneratedThroughDate")
                        .HasColumnType("date")
                        .HasColumnName("generated_through_date");

                    b.Property<int>("GenerationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("generation_version");

                    b.Property<short?>("IntervalMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("interval_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<short>("LateGraceMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("late_grace_minutes");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<short?>("MinIntervalMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("min_interval_minutes");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("recurrence_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_medication_schedules");

                    b.HasIndex("GeneratedThroughDate")
                        .HasDatabaseName("ix_medication_schedules_generated_through_date")
                        .HasFilter("is_active");

                    b.HasIndex("MedicationId")
                        .HasDatabaseName("ix_medication_schedules_medication_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_medication_schedules_user_id");

                    b.ToTable("medication_schedules", "public", t =>
                        {
                            t.HasCheckConstraint("ck_medication_schedules_day_of_month", "(recurrence_type = 'Monthly' AND day_of_month BETWEEN 1 AND 31) OR (recurrence_type <> 'Monthly' AND day_of_month IS NULL)");

                            t.HasCheckConstraint("ck_medication_schedules_days_of_week_range", "days_of_week BETWEEN 0 AND 127");

                            t.HasCheckConstraint("ck_medication_schedules_doses_per_day", "doses_per_day >= 1");

                            t.HasCheckConstraint("ck_medication_schedules_interval_coherence", "interval_minutes IS NULL OR (anchor_time IS NOT NULL AND doses_per_day >= 1 AND interval_minutes > 0)");

                            t.HasCheckConstraint("ck_medication_schedules_late_grace", "late_grace_minutes >= 0");

                            t.HasCheckConstraint("ck_medication_schedules_period", "end_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_medication_schedules_weekdays_required", "recurrence_type <> 'SpecificWeekDays' OR days_of_week > 0");

                            t.HasCheckConstraint("ck_medication_schedules_weekly_single_day", "recurrence_type <> 'Weekly' OR (days_of_week > 0 AND (days_of_week & (days_of_week - 1)) = 0)");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("DoseOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("dose_occurrence_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("NotificationPreferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_preference_id");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_message_id");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_notification_deliveries");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_notification_deliveries_device_id");

                    b.HasIndex("DoseOccurrenceId")
                        .HasDatabaseName("ix_notification_deliveries_dose_occurrence_id");

                    b.HasIndex("NotificationPreferenceId")
                        .HasDatabaseName("ix_notification_deliveries_notification_preference_id");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notification_deliveries_recipient_user_id_created_at");

                    b.HasIndex("Status", "ScheduledForUtc")
                        .HasDatabaseName("ix_notification_deliveries_scheduled")
                        .HasFilter("status = 'Scheduled'");

                    b.ToTable("notification_deliveries", "public", t =>
                        {
                            t.HasCheckConstraint("ck_notification_deliveries_attempt_count", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<short>("LeadMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("lead_minutes");

                    b.Property<short?>("MaxRepeats")
                        .HasColumnType("smallint")
                        .HasColumnName("max_repeats");

                    b.Property<Guid?>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_start");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<short?>("RepeatIntervalMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("repeat_interval_minutes");

                    b.Property<Guid>("SubjectUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_preferences");

                    b.HasIndex("MedicationId")
                        .HasDatabaseName("ix_notification_preferences_medication_id");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_notification_preferences_recipient_user_id");

                    b.HasIndex("SubjectUserId", "RecipientUserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_preferences_default")
                        .HasFilter("medication_id IS NULL AND deleted_at IS NULL");

                    b.HasIndex("SubjectUserId", "RecipientUserId", "MedicationId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_preferences_medication_override")
                        .HasFilter("medication_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("notification_preferences", "public", t =>
                        {
                            t.HasCheckConstraint("ck_notification_preferences_lead_minutes", "lead_minutes >= 0");

                            t.HasCheckConstraint("ck_notification_preferences_quiet_hours", "(quiet_hours_start IS NULL) = (quiet_hours_end IS NULL)");

                            t.HasCheckConstraint("ck_notification_preferences_repeat", "repeat_interval_minutes IS NULL OR repeat_interval_minutes > 0");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.ReportExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("report_type");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("SubjectUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_user_id");

                    b.HasKey("Id")
                        .HasName("pk_report_exports");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_report_exports_requested_by_user_id");

                    b.HasIndex("SubjectUserId", "GeneratedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_report_exports_subject_user_id_generated_at_utc");

                    b.ToTable("report_exports", "public", t =>
                        {
                            t.HasCheckConstraint("ck_report_exports_period", "period_end >= period_start");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.ScheduleAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<Guid?>("AppliedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_from_date");

                    b.Property<int>("NewGenerationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("new_generation_version");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OccurrencesAffected")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_affected");

                    b.Property<int>("PreviousGenerationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("previous_generation_version");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int>("ShiftMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("shift_minutes");

                    b.Property<Guid?>("TriggeredByOccurrenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_occurrence_id");

                    b.HasKey("Id")
                        .HasName("pk_schedule_adjustments");

                    b.HasIndex("AppliedByUserId")
                        .HasDatabaseName("ix_schedule_adjustments_applied_by_user_id");

                    b.HasIndex("TriggeredByOccurrenceId")
                        .HasDatabaseName("ix_schedule_adjustments_triggered_by_occurrence_id");

                    b.HasIndex("ScheduleId", "AppliedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_schedule_adjustments_schedule_id_applied_at_utc");

                    b.ToTable("schedule_adjustments", "public", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_adjustments_occurrences_affected", "occurrences_affected >= 0");

                            t.HasCheckConstraint("ck_schedule_adjustments_version_progress", "new_generation_version > previous_generation_version");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.ScheduleTimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<short>("SlotOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("slot_order");

                    b.Property<TimeOnly>("TimeOfDay")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_of_day");

                    b.HasKey("Id")
                        .HasName("pk_schedule_time_slots");

                    b.HasIndex("ScheduleId", "SlotOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_schedule_time_slots_schedule_id_slot_order");

                    b.ToTable("schedule_time_slots", "public", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_time_slots_slot_order", "slot_order >= 0");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.SymptomRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<DateOnly>("RecordedLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("recorded_local_date");

                    b.Property<TimeOnly>("RecordedLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("recorded_local_time");

                    b.Property<short?>("Severity")
                        .HasColumnType("smallint")
                        .HasColumnName("severity");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trend");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_symptom_records");

                    b.HasIndex("UserId", "RecordedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_symptom_records_user_id_recorded_at_utc")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("symptom_records", "public", t =>
                        {
                            t.HasCheckConstraint("ck_symptom_records_duration", "duration_minutes IS NULL OR duration_minutes >= 0");

                            t.HasCheckConstraint("ck_symptom_records_severity_range", "severity IS NULL OR severity BETWEEN 0 AND 10");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.VitalReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at_utc");

                    b.Property<DateOnly>("MeasuredLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("measured_local_date");

                    b.Property<TimeOnly>("MeasuredLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("measured_local_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("ValuePrimary")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("value_primary");

                    b.Property<decimal?>("ValueSecondary")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("value_secondary");

                    b.HasKey("Id")
                        .HasName("pk_vital_readings");

                    b.HasIndex("UserId", "Type", "MeasuredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_vital_readings_user_id_type_measured_at_utc")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("vital_readings", "public", t =>
                        {
                            t.HasCheckConstraint("ck_vital_readings_blood_pressure_requires_diastolic", "type <> 'BloodPressure' OR value_secondary IS NOT NULL");

                            t.HasCheckConstraint("ck_vital_readings_secondary_only_blood_pressure", "type = 'BloodPressure' OR value_secondary IS NULL");

                            t.HasCheckConstraint("ck_vital_readings_value_primary_positive", "value_primary > 0");
                        });
                });

            modelBuilder.Entity("Doto.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_users_app_users_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Doto.Domain.Entities.ChildInvite", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "ChildUser")
                        .WithMany()
                        .HasForeignKey("ChildUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_child_invites_app_users_child_user_id");

                    b.HasOne("Doto.Domain.Entities.AppUser", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_child_invites_app_users_parent_user_id");

                    b.Navigation("ChildUser");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Doto.Domain.Entities.Device", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_devices_app_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doto.Domain.Entities.DoseOccurrence", b =>
                {
                    b.HasOne("Doto.Domain.Entities.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dose_occurrences_medications_medication_id");

                    b.HasOne("Doto.Domain.Entities.AppUser", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dose_occurrences_app_users_recorded_by_user_id");

                    b.HasOne("Doto.Domain.Entities.MedicationSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dose_occurrences_medication_schedules_schedule_id");

                    b.HasOne("Doto.Domain.Entities.DoseOccurrence", "SupersededByOccurrence")
                        .WithMany()
                        .HasForeignKey("SupersededByOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dose_occurrences_dose_occurrences_superseded_by_occurrence_");

                    b.HasOne("Doto.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dose_occurrences_app_users_user_id");

                    b.Navigation("Medication");

                    b.Navigation("RecordedByUser");

                    b.Navigation("Schedule");

                    b.Navigation("SupersededByOccurrence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doto.Domain.Entities.HealthCondition", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "User")
                        .WithMany("HealthConditions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_health_conditions_app_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doto.Domain.Entities.Medication", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medications_app_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doto.Domain.Entities.MedicationSchedule", b =>
                {
                    b.HasOne("Doto.Domain.Entities.Medication", "Medication")
                        .WithMany("Schedules")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_schedules_medications_medication_id");

                    b.HasOne("Doto.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_schedules_app_users_user_id");

                    b.Navigation("Medication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doto.Domain.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("Doto.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_deliveries_devices_device_id");

                    b.HasOne("Doto.Domain.Entities.DoseOccurrence", "DoseOccurrence")
                        .WithMany()
                        .HasForeignKey("DoseOccurrenceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_deliveries_dose_occurrences_dose_occurrence_id");

                    b.HasOne("Doto.Domain.Entities.NotificationPreference", "NotificationPreference")
                        .WithMany()
                        .HasForeignKey("NotificationPreferenceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_deliveries_notification_preferences_notificati");

                    b.HasOne("Doto.Domain.Entities.AppUser", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_deliveries_app_users_recipient_user_id");

                    b.Navigation("Device");

                    b.Navigation("DoseOccurrence");

                    b.Navigation("NotificationPreference");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Doto.Domain.Entities.NotificationPreference", b =>
                {
                    b.HasOne("Doto.Domain.Entities.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notification_preferences_medications_medication_id");

                    b.HasOne("Doto.Domain.Entities.AppUser", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_preferences_app_users_recipient_user_id");

                    b.HasOne("Doto.Domain.Entities.AppUser", "SubjectUser")
                        .WithMany()
                        .HasForeignKey("SubjectUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_preferences_app_users_subject_user_id");

                    b.Navigation("Medication");

                    b.Navigation("RecipientUser");

                    b.Navigation("SubjectUser");
                });

            modelBuilder.Entity("Doto.Domain.Entities.ReportExport", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_exports_app_users_requested_by_user_id");

                    b.HasOne("Doto.Domain.Entities.AppUser", "SubjectUser")
                        .WithMany()
                        .HasForeignKey("SubjectUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_exports_app_users_subject_user_id");

                    b.Navigation("RequestedByUser");

                    b.Navigation("SubjectUser");
                });

            modelBuilder.Entity("Doto.Domain.Entities.ScheduleAdjustment", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "AppliedByUser")
                        .WithMany()
                        .HasForeignKey("AppliedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_schedule_adjustments_app_users_applied_by_user_id");

                    b.HasOne("Doto.Domain.Entities.MedicationSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_adjustments_medication_schedules_schedule_id");

                    b.HasOne("Doto.Domain.Entities.DoseOccurrence", "TriggeredByOccurrence")
                        .WithMany()
                        .HasForeignKey("TriggeredByOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_schedule_adjustments_dose_occurrences_triggered_by_occurren");

                    b.Navigation("AppliedByUser");

                    b.Navigation("Schedule");

                    b.Navigation("TriggeredByOccurrence");
                });

            modelBuilder.Entity("Doto.Domain.Entities.ScheduleTimeSlot", b =>
                {
                    b.HasOne("Doto.Domain.Entities.MedicationSchedule", "Schedule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_time_slots_medication_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Doto.Domain.Entities.SymptomRecord", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_records_app_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doto.Domain.Entities.VitalReading", b =>
                {
                    b.HasOne("Doto.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vital_readings_app_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Doto.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("HealthConditions");
                });

            modelBuilder.Entity("Doto.Domain.Entities.Medication", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Doto.Domain.Entities.MedicationSchedule", b =>
                {
                    b.Navigation("TimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
